<#
X-Tier1: user
X-Agent: copilot
X-Domain: os1p1ops
X-Purpose: replay-audit
X-Version: v2025.10.11
X-Policy: filename+header compliance required
#>
# SEC-COMMS Zeta - Neural Replay Audit Script
# Verifies embeddings directory and lists recent replay files
# PowerShell 5.1 compatible (ASCII-safe)

$ErrorActionPreference = "Stop"
$embPath = "data\embeddings"
$reportDir = "docs\reports"
$reportPath = "$reportDir\user.copilot.os1p2replay.audit.v2025.10.12.md"

# ANSI colors (if supported)
$supportsAnsi = $host.UI.SupportsVirtualTerminal
function Write-Color($text, $color) {
    if ($supportsAnsi) {
        $colors = @{ "green" = "`e[32m"; "yellow" = "`e[33m"; "cyan" = "`e[36m"; "reset" = "`e[0m" }
        Write-Host "$($colors[$color])$text$($colors['reset'])"
    }
    else {
        Write-Host $text
    }
}

Write-Host ""
Write-Color "SEC-COMMS Zeta - Neural Replay Audit" "cyan"
Write-Host "======================================="
Write-Host ""

# Check embeddings directory
if (-Not (Test-Path $embPath)) {
    Write-Color "[WARN] Embeddings directory not found: $embPath" "yellow"
    $embDirStatus = "Not initialized"
    $fileCount = 0
    $recentFiles = @()
}
else {
    Write-Color "[OK] Embeddings directory exists: $embPath" "green"
    $embDirStatus = "Initialized"
    $files = Get-ChildItem -Path $embPath -Filter "*.json" -File -ErrorAction SilentlyContinue
    $fileCount = $files.Count
    
    if ($fileCount -gt 0) {
        Write-Color "[OK] Found $fileCount embedding file(s)" "green"
        $recentFiles = $files | Sort-Object LastWriteTime -Descending | Select-Object -First 5
        Write-Host ""
        Write-Host "Recent embeddings (top 5):"
        foreach ($file in $recentFiles) {
            $ts = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss")
            $size = "{0:N2}" -f ($file.Length / 1KB)
            Write-Host "  - $($file.Name) ($size KB) | $ts"
        }
    }
    else {
        Write-Color "[INFO] No embeddings found yet" "yellow"
        $recentFiles = @()
    }
}

# Generate report
if (-Not (Test-Path $reportDir)) {
    New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

$reportContent = @"
# SEC-COMMS Zeta - Neural Replay Audit Report
**Date**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Spec**: ``user.copilot.os1p2replay.spec.v2025.10.12.md``

## Summary
- **Directory**: ``$embPath``
- **Status**: $embDirStatus
- **File Count**: $fileCount

## Recent Embeddings (Top 5)
"@

if ($recentFiles.Count -gt 0) {
    foreach ($file in $recentFiles) {
        $ts = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss")
        $size = "{0:N2}" -f ($file.Length / 1KB)
        $reportContent += "`n- ``$($file.Name)`` ($size KB) | $ts"
    }
}
else {
    $reportContent += "`n*(No embeddings found)*"
}

$reportContent += @"


## Compliance Notes
- Embeddings are **learned memories** derived from vault replay
- May contain sensitive context from agent decisions
- **MUST NOT** be versioned or transmitted without explicit authorization
- Rotation recommended: keep last 100 embeddings (see ``rotateEmbeddings()`` in replay-engine.ts)

## Actions Performed
- Verified embeddings directory structure
- Listed recent embedding files by timestamp
- Generated audit report

---
*Generated by: ``scripts/tools/os1_replay_audit.ps1``*
*Audit Version: zeta-v1*
"@

# Write report
Set-Content -Path $reportPath -Value $reportContent -Encoding ASCII
Write-Host ""
Write-Color "[OK] Audit report generated: $reportPath" "green"

# Final summary
Write-Host ""
Write-Host "======================================="
Write-Host "Audit Complete"
Write-Host "======================================="
Write-Host ""
