<#
X-Tier1: user
X-Agent: copilot
X-Domain: os1p1ops
X-Purpose: telemetry-smoke
X-Version: v2025.10.12
X-Policy: filename+header compliance required
#>
# OS One — Telemetry Smoke Test (η)
# Verifies /api/telemetry and /telemetry page reachability
# PowerShell 5.1 compatible (ASCII-safe)

Param(
    [string]$Base = "http://localhost:4000",
    [string]$Out = "docs\reports\user.copilot.os1p1webui.telemetry-smoke.v2025.10.12.md"
)

$ErrorActionPreference = "Stop"

function Row($k, $v) {
    "| $k | $v |"
}

Write-Host ""
Write-Host "SEC-COMMS Telemetry (eta) - Smoke Test"
Write-Host "======================================="
Write-Host "Base: $Base"
Write-Host ""

# Test /api/telemetry endpoint
Write-Host "Testing GET /api/telemetry..."
try {
    $apiResponse = Invoke-WebRequest -UseBasicParsing -Uri "$Base/api/telemetry"
    $okApi = $apiResponse.StatusCode -eq 200
    Write-Host "  Status: $($apiResponse.StatusCode)"
}
catch {
    $okApi = $false
    Write-Host "  Status: Failed"
}

# Test /telemetry page
Write-Host "Testing GET /telemetry..."
try {
    $pageResponse = Invoke-WebRequest -UseBasicParsing -Uri "$Base/telemetry"
    $okPage = $pageResponse.StatusCode -ge 200 -and $pageResponse.StatusCode -lt 500
    Write-Host "  Status: $($pageResponse.StatusCode)"
}
catch {
    $okPage = $false
    Write-Host "  Status: Failed"
}

# Generate report
$apiCheck = if ($okApi) { "✅" } else { "❌" }
$pageCheck = if ($okPage) { "✅" } else { "❌" }

$lines = @(
    "# OS One — Telemetry Smoke (η) · v2025.10.12",
    "**Date**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    "**Base URL**: ``$Base``",
    "",
    "| Check | OK |",
    "|---|:---:|",
    (Row "GET /api/telemetry" $apiCheck),
    (Row "GET /telemetry" $pageCheck),
    "",
    "## Endpoint Details",
    "",
    "### /api/telemetry",
    "- **Purpose**: Consolidated metrics (vault, embeddings, security)",
    "- **Runtime**: Node.js",
    "- **Response**: JSON with ts, vault, embeddings, security fields",
    "",
    "### /telemetry",
    "- **Purpose**: Live dashboard with SSE heartbeat, vault status, embeddings count",
    "- **Runtime**: Client-side React (no external libs)",
    "- **Features**: Sparkline visualization, polling every 4s",
    "",
    "---",
    "*Generated by: ``scripts/tools/user.copilot.os1p1webui.telemetry-smoke.v2025.10.12.ps1``*"
)

# Ensure output directory exists
$outDir = Split-Path $Out
if (-not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

# Write report
Set-Content -Path $Out -Value ($lines -join "`r`n") -Encoding UTF8

Write-Host ""
Write-Host "Report generated: $Out"
Write-Host ""
Write-Host "======================================="
Write-Host "Summary:"
Write-Host "  /api/telemetry: $(if($okApi){'✅ OK'}else{'❌ FAIL'})"
Write-Host "  /telemetry:     $(if($okPage){'✅ OK'}else{'❌ FAIL'})"
Write-Host "======================================="
Write-Host ""
